_BASE_: "Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  MASK_ON: True
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
INPUT:
  FORMAT: "RGB"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02